### ISSUE TITLE
Replace master branch with kotlin branch.

### ISSUE THREAD

**Issue by mrzzy** [MoonCheesez/sstannouncer#3]
# Feature Request: Move kotlin branch to Master
There isn't a point to keeping the master branch.
@joeltio, Also its a great opportunity to show off your brand new shiny `kotlin` code.

**Comment by joeltio** [comment]
Yeah, also looks like there isn't a point in keeping the dev branch as well. I'm not sure why but we have a dev, master and release branch all at the same time.

I'll merge in the kotlin branch and delete the dev branch later
